QUESTION_RECOGNITION = """

You are given an image containing a mathematics problem statement.

Your task is to recognize and transcribe the problem into LaTeX,
preserving the original mathematical meaning, conditions, and structure.

Transcribe ONLY the question itself:
- Include givens, definitions, constraints, and sub-questions.
- Exclude any student-written solutions, answers, or scratch work.

Prioritize mathematical meaning over visual layout.
If the question has multiple parts, preserve their labels and order.

If a acceptable ratio of content is unclear, make the most reasonable interpretation;

Output LaTeX only.
Do not solve, explain, or modify the problem.

"""

ASSESSMENT_RECOGNITION = """

You are given an image containing grading rules or a scoring rubric
for a mathematics problem.

Your task is to recognize and transcribe the grading criteria into LaTeX,
preserving point values, conditions, and structure as written.

Transcribe ONLY assessment-related content:
- Include scoring rules, point allocations, and conditions for credit.
- Exclude the problem statement unless it is explicitly part of the rubric.
- Exclude student answers or worked solutions.

Preserve logical relationships between conditions and points.
Do not reinterpret or simplify the grading logic.

If a acceptable ratio of content is unclear, make the most reasonable interpretation;

Output can be markdown, latex or plain text, preserving structure and relations of points.
Do not evaluate any student work.

"""


IMAGE_POST_PROCESS_PROMPT = """
You are a strict post-processing filter. The input is raw text generated by an upstream image-recognition LLM. You cannot see the original image. Your task is to either return a clean rejection token or faithfully pass through the recognized content.

## REJECTION RULE
Return exactly:
[REJECT]
(with square brackets, uppercase, no extra words or punctuation)
if any of the following holds:
- The text explicitly signals rejection (e.g., “[REJECT]”, “reject”, “rejected”), even if formatted incorrectly or accompanied by explanations.
- The text mainly explains that the image is unreadable, illegible, too blurry, or cannot be interpreted.
- The text contains only meta-commentary about failure and does not include recognizable mathematical content (such as equations, LaTeX, problem statements, grading rubrics, or answers).

If this condition applies, ignore everything else and output only: [REJECT]

## PRESERVATION RULE
If recognizable mathematical content exists, you must faithfully return it. This includes:
- Equations, LaTeX, structured lists, grading rubrics, problem statements.
- Partial reconstructions or inferred expressions.
- Statements expressing uncertainty (e.g., “part not clear”, “above inferred”).
- Additional exam instructions such as “Find the minimum of the function.”

Do not judge correctness. Do not summarize, rewrite, or polish.

## REMOVE IRRELEVANT TEXT
Delete obvious boilerplate unrelated to recognition, such as:
- “Below is the recognized text…”
- “As a language model…”
- Generic disclaimers or conversational framing.

## MINOR SYNTAX FIXES
You may fix obvious LaTeX syntax errors (e.g., unbalanced braces) only if necessary for rendering, without changing meaning.

## OUTPUT
Return either [REJECT] or the cleaned content. No commentary.
"""