QUESTION_RECOGNITION = """

You are given an image containing a mathematics problem statement.

Your task is to recognize and transcribe the problem into LaTeX,
preserving the original mathematical meaning, conditions, and structure.

Transcribe ONLY the question itself:
- Include givens, definitions, constraints, and sub-questions.
- Exclude any student-written solutions, answers, or scratch work.

Prioritize mathematical meaning over visual layout.
If the question has multiple parts, preserve their labels and order.

If a acceptable ratio of content is unclear, make the most reasonable interpretation;

Output LaTeX only.
Do not solve, explain, or modify the problem.

"""

ASSESSMENT_RECOGNITION = """

You are given an image containing grading rules or a scoring rubric
for a mathematics problem.

Your task is to recognize and transcribe the grading criteria into a
deduction-based rubric, preserving point values, conditions, and structure
as written.

# Grading Model (IMPORTANT)

This rubric always follows a **deduction-based** grading model:
- There is a single total/full score for the problem.
- Every other criterion is a point deduction from that total (zero
  deduction for a fully-correct case, with no penalty).
- Do NOT treat several listed point values as additive components that sum
  up to the total — the total is a single number, not a sum of the listed
  items.

# Rules:

## Determine the total score
- If the image explicitly states a total/full score (e.g. "Total: 5 points", "Full marks: 10", "满分5分"), extract that exact value as the total score.
- If no total/full score is stated anywhere in the image, assume the total score is 5.0.

## Transcribe the remaining criteria as deduction items
- Include scoring rules and the conditions under which points are deducted.
- Any point value preceded by a minus sign is a deduction. Treat the minus sign as indicating a negative point value, not as a structural bullet or formatting marker — this holds whether or not there is a space between the "-" and the number that follows (e.g. "-2.5: wrong formula" and "- 2.5: wrong formula" both mean a deduction of 2.5, NOT a bullet-list item reading "2.5: wrong formula").
- Every listed criterion (other than the total/full score) is always a deduction, even when its point value is written with no leading "-" or sign at all (e.g. a line reading "2.5: wrong formula" with no minus sign still means a deduction of 2.5, never a positive credit to add).
- A criterion describing a fully-correct case with no penalty should be transcribed with a point value of 0.0 (equivalently written as "-0.0" in the source — both mean zero deduction, not the total/full score).
- Do NOT list the total/full score itself as one of these criteria — it belongs only in the total score, not in the deduction list.

## Exclude:

- The problem statement, unless it is explicitly part of the rubric.
- Student answers, Worked solutions or solution explanations, unless they are explicitly used as grading criteria.

# Important:

- Preserve logical relationships between conditions and deductions.
- Do not reinterpret or simplify the grading logic.
- If a acceptable ratio of content is unclear, make the most reasonable interpretation;

# Exmple Output:
  ```
  {
    "total_score": 5.0,
    "rubrics": [
      { "points": 0.0, "content": "Correct" },
      { "points": -2.5, "content": "incorrect application of the formula" },
      { "points": -4.0, "content": "use the wrong numbers or values" }
    ]
  }
  ```

# Example of ambiguous dash formatting:

  Given source text (no explicit total/full score stated):
  ```
  -0.0: all correct
  -2.5: use the wrong formula
  -0.5: miss the edge cases
  ```
  The leading "-" on each line is the sign of the point value, not a bullet
  marker, so this must be transcribed as:
  ```
  {
    "total_score": 5.0,
    "rubrics": [
      { "points": 0.0, "content": "all correct" },
      { "points": -2.5, "content": "use the wrong formula" },
      { "points": -0.5, "content": "miss the edge cases" }
    ]
  }
  ```
  (total_score assumed 5.0 since none was explicitly stated.) The same result
  applies even if the source omitted the leading "-" entirely (e.g. "2.5: use
  the wrong formula") — it is still transcribed as a deduction: `-2.5`.

# Output Format:
- Output can be markdown, latex or plain text, preserving structure and relations of points.
Do not evaluate any student work.

"""


IMAGE_POST_PROCESS_PROMPT = """
You are a strict post-processing filter. The input is raw text generated by an upstream image-recognition LLM. You cannot see the original image. Your task is to either return a clean rejection token or faithfully pass through the recognized content.

## REJECTION RULE
Return exactly:
[REJECT]
(with square brackets, uppercase, no extra words or punctuation)
if any of the following holds:
- The text explicitly signals rejection (e.g., “[REJECT]”, “reject”, “rejected”), even if formatted incorrectly or accompanied by explanations.
- The text mainly explains that the image is unreadable, illegible, too blurry, or cannot be interpreted.
- The text contains only meta-commentary about failure and does not include recognizable mathematical content (such as equations, LaTeX, problem statements, grading rubrics, or answers). Or it only has very minilal valid content that is clearly overshadowed by the rejection message (for example. `\$\\text\{\[illegible\]\}$` or `\cancel{x}`.).

If this condition applies, ignore everything else and output only: [REJECT]

## PRESERVATION RULE
If recognizable mathematical content exists, you must faithfully return it. This includes:
- Equations, LaTeX, structured lists, grading rubrics, problem statements.
- Partial reconstructions or inferred expressions.
- Statements expressing uncertainty (e.g., “part not clear”, “above inferred”).
- Additional exam instructions such as “Find the minimum of the function.”

Do not judge correctness. Do not summarize, rewrite, or polish.

## REMOVE IRRELEVANT TEXT
Delete obvious boilerplate unrelated to recognition, such as:
- “Below is the recognized text…”
- “As a language model…”
- Generic disclaimers or conversational framing.

## MINOR SYNTAX FIXES
You may fix obvious LaTeX syntax errors (e.g., unbalanced braces) only if necessary for rendering, without changing meaning.

## OUTPUT
Return either [REJECT] or the cleaned content. No commentary.
"""