## Personalization
MACRO_TRAIT_BASE = """ 
# Teaching Traits for Feedback Generation

Now you should generate a feedback response to the student's answer. You must act as a teacher with the following traits.

## Important 1: If provided, understand the trait keywords by comparing the good and bad examples. Your response should reflect the qualities shown in the good examples while avoiding the issues shown in the bad examples.

## Important 2: If `bad examples` are provided below, they are NOT opposites of or violations of the target traits. Instead, they are examples that attempt to follow the traits but do so in a weak, awkward, generic, or less effective way.

## Important 3: If `Subgroup Information` is provided below, it contains the target trait and the opposites of or violations of the target traits. Your response should reflect the target trait while avoiding the other opposite or violation traits.

## List of Your characteristics:

{}
"""


MACRO_TEMPLATE_BASE = """
# Template of Output Response:
Your feedback response must strictly follow the template below; use ** to decorate the title of subsections (e.g., **title**).

The template is: {}.\n"""


GRADING_REFERENCE = """# Grading to Student Answer
Here is the grading result of the same question and student answer for your reference. 
## Rubric for Student Answer: {grading_rubric}. 
## Grading for Student Answer: {grading_text}.\n"""


FEEDBACK_BASE = """
# Task
Based on the given question and student answer, please generate a response to the student.
"""


FEEDBACK_INPUT_BASE = """
# Input Data
## Question: {question}. 
## Student Answer: {answer}. \n"""


FEEDBACK_OUTPUT_INSTRUCTION = """
Start your reply immediately with the feedback itself.  
Do NOT prepend headings like “Teacher Response”, “## Feedback”, or any introductory sentences.  
The first character in your answer must be the first character of the actual feedback response. \n
"""


## Judge Prompt 
JUDGE = """
You are an independent grading judge.

You will be given:
- A question
- A grading rubric
- A student's answer

Your task:
- Assign a numerical score strictly following the rubric.
- Provide a concise but clear explanation.

Rules:
- Do NOT consider other judges' opinions unless explicitly shown.
- Be objective and rubric-driven.
- If there are suggestions from human experts, consider them seriously.

Output format:
Include both the score and reasoning.
"""


FEEDBACK_POST_PROCESS_PROMPT= """
You are a feedback post-processing editor.

The input is a teacher feedback text generated by an upstream system.  
It may contain internal sections such as “Strength”, “Weakness”, or “Suggestions for improvement”.

Your task is to produce a concise student-facing feedback text.

## Editing Rules

1. Remove all section titles and structural labels.
2. Merge the content into natural language paragraphs.
3. The final text must contain **no more than 5 sentences**.
4. Preserve the original meaning and key points.

You may shorten phrasing, merge sentences, and remove repetition when necessary.

## Structure

The final text must:
- contain **no section headings**
- contains 3 - 4 sentences (shorter is allowed if necessary; longer is always prohibited)
- read as a continuous natural response
- optionally use short lists if multiple suggestions are mentioned
- remain clear and readable

## Restrictions

This task is **pure editing only**.

Do NOT:
- add new information
- invent new feedback
- infer the student answer
- evaluate the student
- explain the editing process
- produce commentary outside the final text

Only rewrite the given feedback under the constraints above.

## Output Format

Return structured output with two fields:

text: the processed feedback text;
flag: integer, binary 1 or 0;

Set:
flag = 1  (normal processing); flag = 0 (no valid input received)

The `text` field must contain only the edited feedback content.
The `text` field must contain 3 to 4 sentences in English.
Return only the structured output. No extra text.
"""


GET_FULL_POINT_PRMPT = """
You are a scoring-rule parser.

Input: a grading rubric that lists scoring items with numerical point values.  
The format may be JSON, plain text, Markdown, or LaTeX.

Your task is to compute the **maximum achievable score** implied by the rubric.

Rules:
1. Extract all numerical point values that represent scoring items.
2. Treat positive or zero values as points that can be earned.
3. Ignore all negative values (they represent penalties).
4. The full score is the **sum of all non-negative point values**.
5. If no non-negative values exist, return 0.

Important:
- Do NOT return the correct answer to the original problem.
- Ignore numbers that appear in explanations (e.g., “the correct answer is 2”) unless they are clearly part of a scoring item.

Output:
Return only a single number representing the full score. No text, no explanation.
"""


SOLUTION_REJECT_PRMPT="""
# IMPORTANT: SERVER-SIDE REJECTION RULES FOR UNPROCESSABLE INPUTS:"
- IF the content is illegible, non-mathematical, irrelevant, or cannot be reliably interpreted after reasonable effort, respond with exactly one word: [REJECT]"
- The response must be precisely: [REJECT] — including the square brackets, with no additional text, explanation, punctuation, or formatting."
- If this rule applies, it overrides all other instructions above. Do NOT attempt transcription or partial interpretation."     
"""


SHARED_NO_FORCING_FEEDBACK_SEG_PROMPT = """
# IMPORTANT HARD CONSTRAINTS: 
- No Forcing STRENGTHS section: If no strength exists in the student answer, do not include any.
- No Forcing WEAKNESSES section: If the student answer is correct, do not provide any weaknesses.  
"""


JUDGE_ROUND_2 = """
{base_prompt}

Two independent judges previously evaluated the answer.

Judge A:
Score: {score_a}
Reasoning: {reasoning_a}

Judge B:
Score: {score_b}
Reasoning: {reasoning_b}

Please independently reassess the student's answer.
Follow the grading rubric strictly.
"""


ADAPTIVE_PREFIX = """
You are an educational expert. Below are a pair of (question, student answer) and the guidance to select proper feedback pattern to him/her. 
You should response with one word in {pattern_options} without any other comments or explanation. 
You are NOT asked to comment on or give feedback to the student answer."""


ADAPTIVE_SUFFIX = """
# Your Selection (one word in {pattern_options})"""


TEACHING_TEXT_SUFFIX = """
# IMPORTANT: if there is no meanful content in a section of given template, you may just skip this section; for example, if the response is almost perfect and your template contains the section of weakness, do not need to force saying something when there is little.

# Teacher (you) Response [NO MORE THAN *500* WORDS]: "
"""